FROM node:18-alpine AS base
WORKDIR /home/app-vite
COPY package*.json / 

# 生产环境
FROM base AS build-stage
RUN npm install
COPY . .
RUN npm run build

# 开发环境
FROM base AS dev 
ENV NODE_ENV=development 
RUN npm install 
COPY . . 
CMD ["npm", "start"] 